### ISSUE TITLE
Not working?..

### ISSUE THREAD

**Issue by rex-taylor** [Blucknote/CustomUploaders#8]
Error message:
The remote server returned an error: (404) Not Found.

Headers:
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
Content-Length: 55
Content-Type: application/json
Date: Mon, 17 May 2021 19:31:36 GMT
Server: nginx/1.18.0

Response text:
{"ok":false,"error_code":404,"description":"Not Found"}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Blucknote** [comment]
![image](https://user-images.githubusercontent.com/15163043/118859905-6fefb700-b8e3-11eb-9202-ee13814be2ae.png)

Seems working to me. Did you keep bot in url?

**Comment by Blucknote** [comment]
Closing due to inactivity
